# Generated by Django 4.2.14 on 2024-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_taskmodel_is_done_taskmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
